author = Sven Schreiber and Artur Tarassow
email = atecon@posteo.de
version = 0.3
date = 2023-01-27
description = Combine multiple plots to a single graph
tags = C88
min-version = 2021a
public = multiplot
data-requirement = no-data-ok
help = multiplot_help.txt
sample-script = multiplot_sample.inp
depends = extra
