author = Sven Schreiber and Artur Tarassow
email = atecon@posteo.de
version = 0.1
date = 2020-06-07
description = Combine multiple plots to a single graph
tags = C88
min-version = 2020b
public = multiplot
data-requirement = no-data-ok
help = multiplot_help.txt
sample-script = multiplot_sample.inp
depends = extra
